package region

const (
	HEAD_SIZE = 16 //头部长度

	IP_SIZE       = 4  //IP长度
	IPV6_SIZE     = 16 //IPv6长度
	COUNTRY_SIZE  = 2  //国家长度
	REGION_SIZE   = 2  //省份长度
	CITY_SIZE     = 4  //城市长度
	District_SIZE = 4  // 县长度

	T_SIZE      = IP_SIZE + COUNTRY_SIZE + REGION_SIZE + CITY_SIZE + District_SIZE   //总长
	IPV6_T_SIZE = IPV6_SIZE + COUNTRY_SIZE + REGION_SIZE + CITY_SIZE + District_SIZE //ipv6 总长

	FLAG_OFFSET = 0
	IP_OFFSET   = 0

	COUNTRY_OFFSET      = IP_OFFSET + IP_SIZE
	IPV6_COUNTRY_OFFSET = IP_OFFSET + IPV6_SIZE

	REGION_OFFSET      = COUNTRY_OFFSET + COUNTRY_SIZE
	IPV6_REGION_OFFSET = IPV6_COUNTRY_OFFSET + COUNTRY_SIZE

	CITY_OFFSET      = REGION_OFFSET + REGION_SIZE
	IPV6_CITY_OFFSET = IPV6_REGION_OFFSET + REGION_SIZE

	District_OFFSET      = CITY_OFFSET + District_SIZE
	IPV6_DISTRICT_OFFSET = IPV6_CITY_OFFSET + District_SIZE

	LT = -1
	GT = 1
	EQ = 0
)
